Repository be15-4th-project/be15-4th-DAO-NBTI-backend, pull requests merged in 2025-05, with the labels that each got.

#9 init : 검사 엔티티 및 레포지토리 생성
  NBTI/src/main/java/com/dao/nbti/test/domain/aggregate/IsCorrect.java
  NBTI/src/main/java/com/dao/nbti/test/domain/aggregate/TestProblem.java
  NBTI/src/main/java/com/dao/nbti/test/domain/aggregate/TestResult.java
  NBTI/src/main/java/com/dao/nbti/test/domain/repository/TestProblemRepository.java
  NBTI/src/main/java/com/dao/nbti/test/domain/repository/TestResultRepository.java
  NBTI/src/main/java/com/dao/nbti/test/domain/repository/repo.java
Labels: init

#10 init : swagger API 의존성 및 설정 추가
  NBTI/build.gradle
  NBTI/src/main/java/com/dao/nbti/common/config/SwaggerConfig.java
  NBTI/src/main/resources/application.yml
Labels: init

#11 로그인 기능 구현
  NBTI/src/main/java/com/dao/nbti/common/auth/application/controller/AuthController.java
  NBTI/src/main/java/com/dao/nbti/common/auth/application/dto/LoginResponse.java
  NBTI/src/main/java/com/dao/nbti/common/auth/application/service/AuthService.java
  NBTI/src/main/java/com/dao/nbti/common/exception/ErrorCode.java
  NBTI/src/main/java/com/dao/nbti/user/domain/aggregate/User.java
  NBTI/src/main/java/com/dao/nbti/user/domain/repository/UserRepository.java
Labels: feat

#21 feat: 학습 기능 초기 구현 - Entity, Controller, Service, Repository 생성
  NBTI/src/main/java/com/dao/nbti/study/application/controller/StudyController.java
  NBTI/src/main/java/com/dao/nbti/study/application/controller/controller.java
  NBTI/src/main/java/com/dao/nbti/study/application/dto/dto.java
  NBTI/src/main/java/com/dao/nbti/study/application/service/StudyService.java
  NBTI/src/main/java/com/dao/nbti/study/application/service/service.java
  NBTI/src/main/java/com/dao/nbti/study/domain/aggregate/IsCorrect.java
  NBTI/src/main/java/com/dao/nbti/study/domain/aggregate/Study.java
  NBTI/src/main/java/com/dao/nbti/study/domain/aggregate/StudyResult.java
  NBTI/src/main/java/com/dao/nbti/study/domain/repository/StudyRepository.java
  NBTI/src/main/java/com/dao/nbti/study/domain/repository/StudyResultRepository.java
  NBTI/src/main/java/com/dao/nbti/study/domain/repository/repo.java
Labels: feat

#49 feat: 카테고리 엔티티에 분야 설명 컬럼 추가
  NBTI/src/main/java/com/dao/nbti/problem/domain/aggregate/Category.java
  NBTI/src/main/java/com/dao/nbti/study/domain/aggregate/Study.java
Labels: feat

#53 feat : ai로 지능 검사 요청
  NBTI/build.gradle
  NBTI/src/main/java/com/dao/nbti/test/application/controller/TestController.java
  NBTI/src/main/java/com/dao/nbti/test/application/controller/controller.java
  NBTI/src/main/java/com/dao/nbti/test/application/dto/dto.java
  NBTI/src/main/java/com/dao/nbti/test/application/dto/request/AiAnswerCreateRequest.java
  NBTI/src/main/java/com/dao/nbti/test/application/dto/response/AiAnswerResponse.java
  NBTI/src/main/java/com/dao/nbti/test/application/service/TestAiAnswerService.java
  NBTI/src/main/java/com/dao/nbti/test/application/service/TestAiAnswerServiceImpl.java
  NBTI/src/main/java/com/dao/nbti/test/application/service/service.java
  NBTI/src/main/resources/application.yml
Labels: feat

#52 Feature/admin 문제 목록 조회 기능 구현
  NBTI/src/main/java/com/dao/nbti/problem/application/controller/AdminProblemController.java
  NBTI/src/main/java/com/dao/nbti/problem/application/controller/controller.java
  NBTI/src/main/java/com/dao/nbti/problem/application/dto/dto.java
  NBTI/src/main/java/com/dao/nbti/problem/application/dto/request/ProblemSearchRequest.java
  NBTI/src/main/java/com/dao/nbti/problem/application/dto/response/ProblemDTO.java
  NBTI/src/main/java/com/dao/nbti/problem/application/dto/response/ProblemListResponse.java
  NBTI/src/main/java/com/dao/nbti/problem/application/dto/response/ProblemSummaryDTO.java
  NBTI/src/main/java/com/dao/nbti/problem/application/service/AdminProblemService.java
  NBTI/src/main/java/com/dao/nbti/problem/application/service/service.java
  NBTI/src/main/java/com/dao/nbti/problem/domain/repository/ProblemRepositoryCustom.java
  NBTI/src/main/java/com/dao/nbti/problem/domain/repository/ProblemRepositoryImpl.java
Labels: feat

#55 feat: 토큰 재발급 기능 구현
  NBTI/src/main/java/com/dao/nbti/common/auth/application/controller/AuthController.java
  NBTI/src/main/java/com/dao/nbti/common/auth/application/dto/TokenResponse.java
  NBTI/src/main/java/com/dao/nbti/common/auth/application/service/AuthService.java
  NBTI/src/main/java/com/dao/nbti/user/application/dto/UserCreateRequest.java
  NBTI/src/main/java/com/dao/nbti/user/domain/repository/UserRepository.java
  NBTI/src/test/java/com/dao/nbti/common/auth/application/service/AuthServiceTest.java
Labels: feat

#57 fix: JwtTokenProvider 변수명 수정
  NBTI/src/main/java/com/dao/nbti/common/jwt/JwtTokenProvider.java
Labels: fix

#54 feat: 학습 진행 - 문제 제공 api 구현, sql dialect 설정, gitignore 추가
  .gitignore
  NBTI/src/main/java/com/dao/nbti/common/exception/ErrorCode.java
  NBTI/src/main/java/com/dao/nbti/problem/domain/aggregate/AnswerType.java
  NBTI/src/main/java/com/dao/nbti/problem/domain/aggregate/Category.java
  NBTI/src/main/java/com/dao/nbti/problem/domain/aggregate/Problem.java
  NBTI/src/main/java/com/dao/nbti/problem/domain/repository/ProblemRepository.java
  NBTI/src/main/java/com/dao/nbti/study/application/controller/StudyController.java
  NBTI/src/main/java/com/dao/nbti/study/application/dto/response/ProblemResponseDto.java
  NBTI/src/main/java/com/dao/nbti/study/application/service/StudyService.java
  NBTI/src/main/java/com/dao/nbti/study/exception/NoSuchAnswerTypeException.java
  NBTI/src/main/java/com/dao/nbti/study/exception/NoSuchCategoryException.java
  NBTI/src/main/java/com/dao/nbti/study/exception/ProblemNotFoundException.java
  NBTI/src/main/resources/application.yml
Labels: feat

#59 feat: 로그아웃 기능 구현
  NBTI/src/main/java/com/dao/nbti/common/auth/application/controller/AuthController.java
  NBTI/src/main/java/com/dao/nbti/common/auth/application/service/AuthService.java
  NBTI/src/test/java/com/dao/nbti/common/auth/application/service/AuthServiceTest.java
Labels: feat

#58 Feature/admin 문제 상세 조회 기능 구현
  NBTI/src/main/java/com/dao/nbti/problem/application/controller/AdminProblemController.java
  NBTI/src/main/java/com/dao/nbti/problem/application/dto/response/ProblemDTO.java
  NBTI/src/main/java/com/dao/nbti/problem/application/dto/response/ProblemDetailsResponse.java
  NBTI/src/main/java/com/dao/nbti/problem/application/dto/response/ProblemSummaryDTO.java
  NBTI/src/main/java/com/dao/nbti/problem/application/service/AdminProblemService.java
  NBTI/src/main/java/com/dao/nbti/problem/domain/aggregate/AnswerTypeEnum.java
  NBTI/src/main/java/com/dao/nbti/problem/domain/aggregate/Problem.java
  NBTI/src/main/java/com/dao/nbti/problem/exception/ProblemException.java
Labels: feat

#70 refactor : 풀이 문제 확인 로직 수정
  NBTI/src/main/java/com/dao/nbti/study/domain/repository/StudyResultRepository.java
Labels: refactor

#71 refactor : 이의제기 목록 조회 페이지 네이션 추가
  NBTI/src/main/java/com/dao/nbti/objection/application/controller/ObjectionController.java
  NBTI/src/main/java/com/dao/nbti/objection/application/service/ObjectionService.java
  NBTI/src/main/java/com/dao/nbti/objection/application/service/ObjectionServiceImpl.java
  NBTI/src/main/java/com/dao/nbti/objection/domain/repository/ObjectionRepository.java
Labels: refactor

#63 feat: 학습 제출 기능 api 구현
  NBTI/src/main/java/com/dao/nbti/common/exception/ErrorCode.java
  NBTI/src/main/java/com/dao/nbti/study/application/controller/StudyController.java
  NBTI/src/main/java/com/dao/nbti/study/application/dto/request/SubmitStudyRequestDto.java
  NBTI/src/main/java/com/dao/nbti/study/application/dto/response/SubmitStudyResponseDto.java
  NBTI/src/main/java/com/dao/nbti/study/application/service/StudyService.java
  NBTI/src/main/java/com/dao/nbti/user/domain/aggregate/PointHistory.java
  NBTI/src/main/java/com/dao/nbti/user/domain/aggregate/User.java
  NBTI/src/main/java/com/dao/nbti/user/domain/repository/PointHistoryRepository.java
Labels: feat

#74 fix : testResult 엔티티 수정
  NBTI/src/main/java/com/dao/nbti/test/domain/aggregate/IsSaved.java
  NBTI/src/main/java/com/dao/nbti/test/domain/aggregate/TestResult.java
Labels: fix

#72 [feat #033] 관리자 이의 제기 목록 조회 기능 구현
  NBTI/src/main/java/com/dao/nbti/objection/application/controller/AdminObjectionController.java
  NBTI/src/main/java/com/dao/nbti/objection/application/dto/request/AdminObjectionSearchRequest.java
  NBTI/src/main/java/com/dao/nbti/objection/application/dto/response/AdminObjectionDTO.java
  NBTI/src/main/java/com/dao/nbti/objection/application/dto/response/AdminObjectionListResponse.java
  NBTI/src/main/java/com/dao/nbti/objection/application/service/AdminObjectionService.java
  NBTI/src/main/java/com/dao/nbti/objection/domain/repository/ObjectionRepositoryCustom.java
  NBTI/src/main/java/com/dao/nbti/objection/domain/repository/ObjectionRepositoryImpl.java
Labels: feat

#73 feat: 학습 결과 조회 api 구현
  NBTI/src/main/java/com/dao/nbti/common/exception/ErrorCode.java
  NBTI/src/main/java/com/dao/nbti/study/application/controller/StudyController.java
  NBTI/src/main/java/com/dao/nbti/study/application/dto/response/StudyResultDetailResponseDto.java
  NBTI/src/main/java/com/dao/nbti/study/application/service/StudyService.java
  NBTI/src/main/java/com/dao/nbti/study/exception/InvalidAccessException.java
  NBTI/src/main/java/com/dao/nbti/study/exception/StudyNotFoundException.java
  NBTI/src/main/java/com/dao/nbti/study/exception/StudyResultNotFoundException.java
Labels: feat

#75 feat: 관리자 이의 제기 상세 조회 기능 구현
  NBTI/src/main/java/com/dao/nbti/objection/application/controller/AdminObjectionController.java
  NBTI/src/main/java/com/dao/nbti/objection/application/dto/response/AdminObjectionDTO.java
  NBTI/src/main/java/com/dao/nbti/objection/application/dto/response/AdminObjectionDetailResponse.java
  NBTI/src/main/java/com/dao/nbti/objection/application/dto/response/AdminObjectionDetailsDTO.java
  NBTI/src/main/java/com/dao/nbti/objection/application/service/AdminObjectionService.java
Labels: feat

#78 refactor : 검사 결과 목록 조회에 새로이 추가된 isSaved 조건 검색 추가
  NBTI/src/main/java/com/dao/nbti/test/domain/repository/TestResultRepository.java
Labels: refactor

#76 feat: 비밀번호 찾기 및 재설정 기능 구현
  NBTI/src/main/java/com/dao/nbti/common/auth/application/controller/AuthController.java
  NBTI/src/main/java/com/dao/nbti/common/auth/application/dto/PasswordFindRequest.java
  NBTI/src/main/java/com/dao/nbti/common/auth/application/dto/PasswordResetRequest.java
  NBTI/src/main/java/com/dao/nbti/common/auth/application/service/AuthService.java
  NBTI/src/main/java/com/dao/nbti/common/auth/domain/aggregate/TempToken.java
  NBTI/src/main/java/com/dao/nbti/common/config/RedisConfig.java
  NBTI/src/main/java/com/dao/nbti/common/exception/ErrorCode.java
  NBTI/src/main/java/com/dao/nbti/user/domain/repository/UserRepository.java
Labels: feat

#80 refactor: isSaved 타입 오류 수정
  NBTI/src/main/java/com/dao/nbti/test/domain/repository/TestResultRepository.java
Labels: refactor

#83 fix: 회원가입 및 비밀번호 재설정 기능 수정
  NBTI/src/main/java/com/dao/nbti/common/auth/application/dto/PasswordResetRequest.java
  NBTI/src/main/java/com/dao/nbti/user/application/controller/UserController.java
  NBTI/src/main/java/com/dao/nbti/user/application/dto/UserCreateRequest.java
Labels: fix

#79 feat: 학습 조회 - 학습 분야 목록 조회 api 구현
  NBTI/src/main/java/com/dao/nbti/problem/domain/repository/CategoryRepository.java
  NBTI/src/main/java/com/dao/nbti/study/application/controller/StudyController.java
  NBTI/src/main/java/com/dao/nbti/study/application/dto/response/StudyCategoryListResponseDto.java
  NBTI/src/main/java/com/dao/nbti/study/application/service/StudyService.java
Labels: feat

#81 feat: 이의 제기 처리 기능 구현
  NBTI/src/main/java/com/dao/nbti/common/exception/ErrorCode.java
  NBTI/src/main/java/com/dao/nbti/objection/application/controller/AdminObjectionController.java
  NBTI/src/main/java/com/dao/nbti/objection/application/dto/request/ObjectionUpdateRequest.java
  NBTI/src/main/java/com/dao/nbti/objection/application/dto/response/ObjectionUpdateResponse.java
  NBTI/src/main/java/com/dao/nbti/objection/application/service/AdminObjectionService.java
  NBTI/src/main/java/com/dao/nbti/objection/domain/aggregate/Objection.java
  NBTI/src/main/java/com/dao/nbti/problem/application/controller/AdminCategoryController.java
  NBTI/src/main/java/com/dao/nbti/problem/application/dto/response/CategoryResponse.java
  NBTI/src/main/java/com/dao/nbti/problem/application/dto/response/CategorySummaryDTO.java
  NBTI/src/main/java/com/dao/nbti/problem/application/service/AdminProblemService.java
  NBTI/src/main/java/com/dao/nbti/problem/domain/repository/CategoryRepository.java
Labels: feat

#84 feat: 회원 정보 조회 기능 구현
  NBTI/src/main/java/com/dao/nbti/user/application/controller/UserController.java
  NBTI/src/main/java/com/dao/nbti/user/application/dto/UserInfoResponse.java
  NBTI/src/main/java/com/dao/nbti/user/application/service/UserService.java
Labels: feat

#82 feat : 마이페이지에 검사 결과 저장 기능
  NBTI/src/main/java/com/dao/nbti/common/exception/ErrorCode.java
  NBTI/src/main/java/com/dao/nbti/common/exception/GlobalExceptionHandler.java
  NBTI/src/main/java/com/dao/nbti/test/application/controller/TestController.java
  NBTI/src/main/java/com/dao/nbti/test/application/service/TestAiAnswerServiceImpl.java
  NBTI/src/main/java/com/dao/nbti/test/application/service/TestService.java
  NBTI/src/main/java/com/dao/nbti/test/application/service/TestServiceImpl.java
  NBTI/src/main/java/com/dao/nbti/test/domain/aggregate/TestResult.java
  NBTI/src/main/java/com/dao/nbti/user/domain/repository/UserRepository.java
  NBTI/src/test/java/com/dao/nbti/test/application/service/TestServiceImplTest.java
Labels: feat

#85 fix : 누락된 메소드 복구
  NBTI/src/main/java/com/dao/nbti/test/domain/repository/TestResultRepository.java
Labels: fix

#87 feat: 회원 목록 조회 기능 구현
  NBTI/src/main/java/com/dao/nbti/user/application/controller/UserController.java
  NBTI/src/main/java/com/dao/nbti/user/application/dto/UserAdminViewDTO.java
  NBTI/src/main/java/com/dao/nbti/user/application/dto/UserAdminViewResponse.java
  NBTI/src/main/java/com/dao/nbti/user/application/dto/UserSearchCondition.java
  NBTI/src/main/java/com/dao/nbti/user/application/service/UserService.java
  NBTI/src/main/java/com/dao/nbti/user/domain/repository/UserRepositoryCustom.java
  NBTI/src/main/java/com/dao/nbti/user/domain/repository/UserRepositoryCustomImpl.java
Labels: feat

#86 feat : 검사 문제 제공 기능 구현 완료
  NBTI/src/main/java/com/dao/nbti/common/exception/ErrorCode.java
  NBTI/src/main/java/com/dao/nbti/problem/domain/repository/ProblemTestRepository.java
  NBTI/src/main/java/com/dao/nbti/test/application/controller/TestController.java
  NBTI/src/main/java/com/dao/nbti/test/application/service/TestService.java
  NBTI/src/main/java/com/dao/nbti/test/application/service/TestServiceImpl.java
  NBTI/src/test/java/com/dao/nbti/test/application/service/TestServiceImplTest.java
Labels: feat

#88 feat: 학습 내역 조회 api 구현
  NBTI/src/main/java/com/dao/nbti/problem/domain/repository/AnswerTypeRepository.java
  NBTI/src/main/java/com/dao/nbti/problem/domain/repository/CategoryRepository.java
  NBTI/src/main/java/com/dao/nbti/problem/domain/repository/ProblemRepository.java
  NBTI/src/main/java/com/dao/nbti/study/application/controller/AdminStudyController.java
  NBTI/src/main/java/com/dao/nbti/study/application/dto/request/StudySearchRequestDto.java
  NBTI/src/main/java/com/dao/nbti/study/application/dto/response/StudySummaryDto.java
  NBTI/src/main/java/com/dao/nbti/study/application/dto/response/StudySummaryListResponseDto.java
  NBTI/src/main/java/com/dao/nbti/study/application/service/StudyService.java
  NBTI/src/main/java/com/dao/nbti/study/domain/repository/StudyRepository.java
  NBTI/src/main/java/com/dao/nbti/study/domain/repository/StudyRepositoryCustom.java
  NBTI/src/main/java/com/dao/nbti/study/domain/repository/StudyRepositoryImpl.java
  NBTI/src/main/java/com/dao/nbti/study/domain/repository/StudyResultRepository.java
Labels: feat

#93 fix: 로그인 HTTP 메소드 수정
  NBTI/src/main/java/com/dao/nbti/common/auth/application/controller/AuthController.java
Labels: bug

#91 feat : 검사 결과 채점 후 결과 및 문제 목록 저장 기능
  NBTI/src/main/java/com/dao/nbti/common/config/RedisConfig.java
  NBTI/src/main/java/com/dao/nbti/problem/domain/repository/CategoryRepository.java
  NBTI/src/main/java/com/dao/nbti/test/application/controller/TestController.java
  NBTI/src/main/java/com/dao/nbti/test/application/controller/TestResultController.java
  NBTI/src/main/java/com/dao/nbti/test/application/dto/request/TestAnswerDTO.java
  NBTI/src/main/java/com/dao/nbti/test/application/dto/request/TestResultCreateRequest.java
  NBTI/src/main/java/com/dao/nbti/test/application/dto/request/TestSubmitRequest.java
  NBTI/src/main/java/com/dao/nbti/test/application/dto/response/TestProblemListResponse.java
  NBTI/src/main/java/com/dao/nbti/test/application/dto/response/TestResponse.java
  NBTI/src/main/java/com/dao/nbti/test/application/service/TestAiAnswerService.java
  NBTI/src/main/java/com/dao/nbti/test/application/service/TestAiAnswerServiceImpl.java
  NBTI/src/main/java/com/dao/nbti/test/application/service/TestService.java
  NBTI/src/main/java/com/dao/nbti/test/application/service/TestServiceImpl.java
  NBTI/src/main/java/com/dao/nbti/user/domain/aggregate/User.java
  NBTI/src/test/java/com/dao/nbti/test/application/service/TestServiceImplTest.java
Labels: feat

#96 refactor: 관리자 문제 등록, 문제 수정시 S3 업로드 구현
  NBTI/build.gradle
  NBTI/src/main/java/com/dao/nbti/common/config/S3Config.java
  NBTI/src/main/java/com/dao/nbti/problem/application/controller/AdminProblemController.java
  NBTI/src/main/java/com/dao/nbti/problem/application/dto/request/ProblemCommandRequest.java
  NBTI/src/main/java/com/dao/nbti/problem/application/dto/request/ProblemCreateRequest.java
  NBTI/src/main/java/com/dao/nbti/problem/application/dto/request/ProblemUpdateRequest.java
  NBTI/src/main/java/com/dao/nbti/problem/application/service/AdminProblemService.java
  NBTI/src/main/java/com/dao/nbti/problem/application/service/S3Service.java
  NBTI/src/main/java/com/dao/nbti/problem/domain/aggregate/Problem.java
  NBTI/src/main/java/com/dao/nbti/study/application/dto/request/StudySearchRequestDto.java
  NBTI/src/main/resources/application.yml
Labels: feat

#101 [fix #100] 회원가입 HTTP 메소드 수정
  NBTI/src/main/java/com/dao/nbti/user/application/controller/UserController.java
Labels: bug

#97 refactor : 사용자 인증 관련 로직 수정
  NBTI/src/main/java/com/dao/nbti/objection/application/controller/ObjectionController.java
  NBTI/src/main/java/com/dao/nbti/objection/application/dto/response/ObjectionSummaryResponse.java
  NBTI/src/main/java/com/dao/nbti/objection/application/service/ObjectionService.java
  NBTI/src/main/java/com/dao/nbti/objection/application/service/ObjectionServiceImpl.java
  NBTI/src/main/java/com/dao/nbti/study/application/controller/StudyResultController.java
  NBTI/src/main/java/com/dao/nbti/study/application/dto/response/StudyProblemDetail.java
  NBTI/src/main/java/com/dao/nbti/study/application/dto/response/StudySummaryListResponseDto.java
  NBTI/src/main/java/com/dao/nbti/study/application/service/StudyResultServiceImpl.java
  NBTI/src/main/java/com/dao/nbti/study/domain/repository/StudyRepository.java
  NBTI/src/main/java/com/dao/nbti/test/application/controller/TestResultController.java
  NBTI/src/main/java/com/dao/nbti/test/application/service/TestResultServiceImpl.java
Labels: refactor

#102 refactor: 문제 목록 조회 시 정렬 로직 추가
  NBTI/src/main/java/com/dao/nbti/problem/domain/repository/ProblemRepositoryImpl.java
Labels: refactor

#105 fix: 백엔드 로직 수정
  NBTI/src/main/java/com/dao/nbti/common/auth/application/controller/AuthController.java
  NBTI/src/main/java/com/dao/nbti/study/application/dto/request/StudySearchRequestDto.java
  NBTI/src/main/java/com/dao/nbti/test/domain/repository/TestRepositoryCustomImpl.java
  NBTI/src/main/java/com/dao/nbti/user/application/controller/UserController.java
  NBTI/src/main/java/com/dao/nbti/user/domain/aggregate/User.java
Labels: fix

#104 [refactor] 학습 결과 조회 시 정답 컬럼 추가
  NBTI/src/main/java/com/dao/nbti/study/application/dto/response/StudyResultDetailResponseDto.java
  NBTI/src/main/java/com/dao/nbti/study/application/service/StudyService.java
Labels: feat

#107 refactor: 학습 문제 조회 시 정답 컬럼 추가
  NBTI/src/main/java/com/dao/nbti/study/application/dto/response/ProblemResponseDto.java
  NBTI/src/main/java/com/dao/nbti/study/application/service/StudyService.java
Labels: refactor

#108 feat : 최신 정렬 적용
  NBTI/src/main/java/com/dao/nbti/study/domain/repository/StudyRepository.java
  NBTI/src/main/java/com/dao/nbti/test/domain/repository/TestResultRepository.java
Labels: feat

#106 [feat] 검사 결과 상세 조회 기능
  NBTI/src/main/java/com/dao/nbti/common/exception/ErrorCode.java
  NBTI/src/main/java/com/dao/nbti/test/application/controller/TestResultController.java
  NBTI/src/main/java/com/dao/nbti/test/application/service/TestAiAnswerServiceImpl.java
  NBTI/src/main/java/com/dao/nbti/test/application/service/TestService.java
  NBTI/src/main/java/com/dao/nbti/test/application/service/TestServiceImpl.java
Labels: feat

#109 fix: 학습 문제 조회 시 isCorrect 검사 로직 제거
  NBTI/src/main/java/com/dao/nbti/study/application/dto/response/StudySummaryDto.java
  NBTI/src/main/java/com/dao/nbti/study/application/service/StudyService.java
  NBTI/src/main/java/com/dao/nbti/study/domain/repository/StudyRepositoryImpl.java
Labels: fix

#110 docs: swagger 주석 추가
  NBTI/src/main/java/com/dao/nbti/objection/application/controller/AdminObjectionController.java
  NBTI/src/main/java/com/dao/nbti/objection/application/dto/request/AdminObjectionSearchRequest.java
  NBTI/src/main/java/com/dao/nbti/objection/application/dto/request/ObjectionUpdateRequest.java
  NBTI/src/main/java/com/dao/nbti/problem/application/controller/AdminProblemController.java
  NBTI/src/main/java/com/dao/nbti/problem/application/dto/request/ProblemCreateRequest.java
  NBTI/src/main/java/com/dao/nbti/problem/application/dto/request/ProblemSearchRequest.java
  NBTI/src/main/java/com/dao/nbti/problem/application/dto/request/ProblemUpdateRequest.java
Labels: docs

#113 fix : 검사 결과 조회 수정
  NBTI/src/main/java/com/dao/nbti/test/application/controller/TestResultController.java
  NBTI/src/main/java/com/dao/nbti/test/application/dto/response/TestResultResponse.java
  NBTI/src/main/java/com/dao/nbti/test/application/service/TestService.java
  NBTI/src/main/java/com/dao/nbti/test/application/service/TestServiceImpl.java
Labels: bug

#115 fix: 회원 탈퇴 request 추가
  NBTI/src/main/java/com/dao/nbti/common/auth/application/controller/AuthController.java
  NBTI/src/main/java/com/dao/nbti/user/application/controller/UserController.java
  NBTI/src/main/java/com/dao/nbti/user/application/dto/UserDeleteRequest.java
  NBTI/src/main/java/com/dao/nbti/user/application/service/UserService.java
  NBTI/src/test/java/com/dao/nbti/user/application/service/UserServiceTest.java
Labels: fix

#118 [docs] Dockerfile, docker-compose 추가
  NBTI/Dockerfile
  docker-compose.yml
Labels: docs

#119 docs: logstash.conf 파일 추가
  docker/logstash/logstash.conf
Labels: docs

#121 chore: backend container 제거, 불필요한 test contextLoad문 제거
  NBTI/src/test/java/com/dao/nbti/NbtiApplicationTests.java
  docker-compose.yml
Labels: chore

#126 feat: logstash, spring actuator 의존성
  NBTI/build.gradle
  NBTI/src/main/resources/application.yml
  NBTI/src/main/resources/logback-spring.xml
Labels: chore

#127 [init] swagger api 인증 허가
  NBTI/src/main/java/com/dao/nbti/common/config/SecurityConfig.java
Labels: init

#129 chore: 로그인 시, slf4j log 출력문 추가
  NBTI/src/main/java/com/dao/nbti/common/auth/application/service/AuthService.java
Labels: chore

#131 chore: 로그아웃 시, slf4j log 출력문 수정
  NBTI/src/main/java/com/dao/nbti/common/auth/application/service/AuthService.java
Labels: chore
